name: Dusk
on: [ push ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dusk:
    runs-on: ubuntu-latest
    env:
      COMPOSER_ALLOW_SUPERUSER: 1
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        php-versions: [ '8.3' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          DEBUG: true
          APP_ENV: "testing"
      - uses: ./.github/actions/setup-php
        with:
          php_version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo, mysql, gd, curl, zip, sqlite, xml, intl, bcmath, json, zlib, openssl, iconv
          coverage: xdebug
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Copy .env.testing to .env
        run: cp .env.testing .env
      - name: Npm install
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - run: npm install
      - run: npm run build
      - name: Remove screenshot layout test
        run: |
          rm -f userfiles/templates/big/src/tests/Browser/BigScreenshotLayoutsTest.php
      - name: Clear bootstrap cache
        run: php artisan optimize:clear
      - name: List env
        run: php artisan env
      - name: List artisan commands
        run: php artisan list
      - name: Run Laravel Server
        #run: php artisan serve-test --env=testing > /dev/null 2>&1 &
        #run: APP_ENV=testing && php -d variables_order=EGPCS -S 127.0.0.1:8000 > /dev/null 2>&1 &
       # run: APP_ENV=testing && php -d variables_order=EGPCS -S 127.0.0.1:8000 > /home/runner/work/microweber/microweber/storage/logs/serve.log 2>&1 &
        run: APP_ENV=testing && php artisan serve-test-code-coverage --ansi --env=testing --no-interaction --quiet &
      - name: Run Dusk Tests
        run: |
          chmod -R 0755 vendor/laravel/dusk/bin/
          composer test:dusk
      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tests/Browser/screenshots
      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: console
          path: tests/Browser/console
      - name: Upload Laravel Storage Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: storage-logs
          path: storage/logs
      - name: Upload Laravel config
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: config
          path: config
